version: '3.8'

services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - task-network
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - task-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_NAME: task_management
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    depends_on:
      - db
      # - auth-service
      # - notification-service
    networks:
      - task-network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: task_management
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network
    ports:
    - "5432:5432"

  # auth-service:
  #   build: ./auth-service
  #   ports:
  #     - "5001:5001"
  #   environment:
  #     - JWT_SECRET=your-secret-key
  #     - DATABASE_URL=postgres://user:password@postgres:5432/taskdb
  #   depends_on:
  #     - postgres
  #   networks:
  #     - task-network

  # notification-service:
  #   build: ./notification-service
  #   ports:
  #     - "5002:5002"
  #   environment:
  #     - SMTP_HOST=smtp.example.com
  #     - SMTP_PORT=587
  #     - SMTP_USER=user
  #     - SMTP_PASS=password
  #   depends_on:
  #     - backend
  #   networks:
  #     - task-network

volumes:
  postgres_data:

secrets:
  db_password:
    file: ./secrets/db_password.txt

networks:
  task-network:
    driver: bridge